title = "Deploy astro version 0.0.1 to alpha"

[environment]
name = "alpha"

[application]
name        = "astro"
source      = "https://bitbucket.org/dnathanturner/astro"
pull_master = true
version     = "0.0.1"

[build]
[build.go]
get = "github.com/fatih/color"
install = "github.com/dnt17/astro"
