title = "Deploy astro version 0.0.1 to alpha"

[environment]
name = "alpha"

[application]
name        = "astro"
source      = "https://bitbucket.org/dnathanturner/astro"
pull_master = true
version     = "0.0.1"

[build]
go = 	[["get", "github.com/containeous/flaeg"],
	["install", "bitbucket.org/dnathanturner/astro"]]
